// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kajirita2002/golang_basis/config"
	"github.com/kajirita2002/golang_basis/domain/service"
	"github.com/kajirita2002/golang_basis/external/entwrapper"
	"github.com/kajirita2002/golang_basis/server/api/grpc/handler"
	"github.com/kajirita2002/golang_basis/usecase"
)

// Injectors from wire.go:

func injector() (*ServiceServer, error) {
	ent, err := config.NewEnt()
	if err != nil {
		return nil, err
	}
	client := newEntClient(ent)
	userImpl := entwrapper.NewUser(client)
	serviceUserImpl := service.NewUser(userImpl)
	usecaseUserImpl := usecase.NewUser(serviceUserImpl)
	user := handler.NewUser(usecaseUserImpl)
	serviceServer := newServer(user)
	return serviceServer, nil
}
